### ISSUE TITLE
IE8: Use of event.charCode in DropDown not supported by legacy IE

### ISSUE THREAD

**Issue by Jemt** [Jemt/Fit.UI#113]
Due to use of unsupported (in IE8) _charCode_ property in DropDown, input fields in the DropDown does not assume the correct width when typing, causing characters to become hidden.

![image](https://user-images.githubusercontent.com/1258714/100836380-7ee6c800-346f-11eb-97eb-011129fb9626.png)

We could probably do something like `var charCode = ev.charCode !== undefined ? ev.charCode : ev.keyCode` instead. _However_, charCode only contains a value when a real character is pressed while keyCode always has a keyCode representing the key pressed. But it seems, according to spec (https://developer.mozilla.org/en-US/docs/Web/API/Document/keypress_event), that OnKeyPress should only be fired when character keys are pressed:
"_The keypress event is fired when a key that produces a character value is pressed down._"
The ENTER key (also in combination with SHIFT and CTRL) seems to be an exception to this. It does not fire for e.g. Backspace, Delete, Function keys, etc. when tested with Chrome 86 on macOS. If this is also the case on Linux and Windows, using the keyCode instead should be fine - in that case we can completely ignore charCode.

Test with `ev.keyCode` on Mac, Windows, and Linux in various browsers, and make sure to ignore the ENTER key (keyCode 13).

**Comment by Jemt** [comment]
Both charCode and keyCode are deprecated. We should probably expose `Fit.Events.GetKeyCode(evArg)` which uses modern APIs when available, and revert to legacy APIs when not. Also supply `Fit.Events.GetKeyChar(evArg)` which on modern browsers leverage the .key property, while on older browsers use something like `String.fromCharCode(evArg.charCode || evArg.keyCode)`

**Comment by FlowIT-JIT** [comment]
This issue is no longer relevant since the introduction of a new layout model for selected items. The code has been removed.
The suggested implementation of Fit.Events.GetKeyCode(..) and Fit.Events.GetKeyChar(..) has been moved to a new issue: #123
