### ISSUE TITLE
Fit.Http lacks support for passing credentials to a foreign domain (withCredentials)

### ISSUE THREAD

**Issue by Jemt** [Jemt/Fit.UI#13]
The XMLHttpRequest.withCredentials property is a Boolean that indicates whether or not cross-site Access-Control requests should be made using credentials such as cookies, authorization headers or TLS client certificates.

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials

**Comment by FlowIT-JIT** [comment]
Recommending something like:

```
req.RequestProperties({
    withCredentials: true
});
```

Make it clear that cross browser support is not guaranteed for RequestProperties - for instance the example above is not supported in IE9 and older.

**Comment by Jemt** [comment]
This has already been implemented:
https://github.com/Jemt/Fit.UI/commit/56b1630e6d549480e01a1e527bf63a4d8d5e298d#diff-f9e13ea1c33c5a47a6cd7c88131fd5b8
