### ISSUE TITLE
Typings - problems with nested types

### ISSUE THREAD

**Issue by Jemt** [Jemt/Fit.UI#16]
Nested classes such as Fit.Controls.TreeView.Node are not supported in typings (Fit and Controls are declared as namespaces and not classes). To work around this we currently move nested classes and enums to an alternative namespace and declare a property of the moved type on the parent class. For instance _Fit.Controls.TreeView.Node_ is declared like so on the TreeView class:
public static Node : typeof __FitInternals.FitControlsTreeViewNode;

Unfortunately this prevents us from type casting like so:
(obj as Fit.Controls.TreeView.Node).AddChild(..);
or like so:
tree.OnSelect((sender:Fit.Controls.TreeView, node:**Fit.Controls.TreeView.Node**) => {});

Furthermore Enums are declared as interfaces on the internal namespace as they too cannot be nested within classes. They are also implemented like properties:
public Type(val?:typeof Fit.Controls.Button.Type[keyof __FitInternals.IFitControlsButtonType]):typeof Fit.Controls.Button.Type[keyof __FitInternals.IFitControlsButtonType];

The way Enums are implemented results in Enum values not being considered a common type - take this example:
var type = Fit.Controls.Input.Type.Color;
type = Fit.Controls.Input.Type.Email;
The second assignment produces the following error: [ts] Type '"Email"' is not assignable to type '"Color"'.

**Comment by FlowIT-JIT** [comment]
These problems have been addressed in the following commits:
https://github.com/Jemt/Fit.UI/commit/d0e038ad5d2fb8383fadba04ede97be7d7497805, https://github.com/Jemt/Fit.UI/commit/2e5dbfa8c43bc753b4b670fd54e24a5b76aa1f9b, https://github.com/Jemt/Fit.UI/commit/436d9904d4671d62145edf53d1e4f6875d677e3d .

Fit.UI has been refactored while ensuring backward compatibility for JS applications.

TypeScript applications will need to search and replace the following types:

Fit.Controls.Button.Type				=>	Fit.Controls.ButtonType
Fit.Controls.Input.Type					=>	Fit.Controls.InputType
Fit.Controls.WSTreeView.SelectAllMode	=>	Fit.Controls.WSTreeViewSelectAllMode
Fit.Controls.TreeView.Node				=>	Fit.Controls.TreeViewNode
Fit.Controls.ContextMenu.Item			=>	Fit.Controls.ContextMenuItem

**Comment by Jemt** [comment]
Issue resolved - closing.
