### ISSUE TITLE
DatePicker: Show() throws error if not mounted in DOM

### ISSUE THREAD

**Issue by Jemt** [Jemt/Fit.UI#186]
The DatePicker control throws an error if Show() is called while control is not mounted.

`new Fit.Controls.DatePicker().Show()`

![image](https://user-images.githubusercontent.com/1258714/235372222-02115873-6bab-4599-91c2-0f520ba43087.png)

**Comment by FlowIT-JIT** [comment]
Turns out the error is also thrown if mounted, but at the same time not visible (part of render tree).
