### ISSUE TITLE
Variable "elm" is used before it has been defined

### ISSUE THREAD

**Issue by kollster** [Jemt/Fit.UI#198]
I get the following error when trying to use fit-ui:

```
Fit.UI.js:23754 
 Uncaught (in promise) ReferenceError: elm is not defined
    at Fit.Controls.Input.Focused (Fit.UI.js:23754:3)
    at Fit.Controls.Input.MultiLine (Fit.UI.js:24426:22)
    at Fit.Controls.Input.DesignMode (Fit.UI.js:25058:9)
    at control-factory.ts:2726:7
    at control-factory.ts:2734:1
```

It appears that a value is being assigned to elm before it has been defined. It happens on line 23754 in Fit.UI.js.

```js
elm = input;
```

It works, if you change the line to:

```js
let elm = input;
```

Below is an excerpt of the problematic area:

![image](https://github.com/Jemt/Fit.UI/assets/3436707/472a2454-d2ba-4019-9b62-350041cc3443)

**Comment by FlowIT-JIT** [comment]
Thanks for the fix - it has now been merged and a new NPM package has been released: version 2.17.3
