### ISSUE TITLE
Fit.Browser.GetQueryString(..) should decode parameter keys

### ISSUE THREAD

**Issue by Jemt** [Jemt/Fit.UI#20]
See source code for Fit.Browser.GetQueryString(..):
https://github.com/Jemt/Fit.UI/blob/master/Core/Browser.js#L125

Notice how parameter values are decoded but parameter keys are not. This seems wrong since both keys and values may contain encoded characters.

**Comment by FlowIT-JIT** [comment]
Fixed with commit https://github.com/Jemt/Fit.UI/commit/8a78eb2f7e0bf1d6dcce4a50c83e88d52717f898
