### ISSUE TITLE
Input in DesignMode (HTML editor) does not respect Spell Checking option

### ISSUE THREAD

**Issue by Jemt** [Jemt/Fit.UI#21]
See JSFiddle that demonstrates the problem and suggests a fix:
https://fiddle.jshell.net/gnnxt31t/3/

**Comment by Jemt** [comment]
See https://docs.ckeditor.com/ckeditor4/latest/guide/dev_spellcheck.html#native-browser-spell-checker - use this solution to enable spell checking rather than manipulating CKEditor's DOM !

**Comment by FlowIT-JIT** [comment]
Fixed
