### ISSUE TITLE
WSDropDown.Dispose not disposing properly

### ISSUE THREAD

**Issue by FlowIT-JIT** [Jemt/Fit.UI#3]
When calling Dispose() on WSDropDown, not all internal resources are cleaned up properly. Creating a new control with the same ID is not possible - an error is emitted:

ThrowError: Control with ID 'CTL_DropDown1__WSListView' has already been defined - Control IDs must be unique!

Also, DropDown, from which WSDropDown inherits, defines an OnClick handler on 'document' which is not removed when disposing control, causing an error when clicking anywhere on the page after the control is disposed. Search for the code below in DropDown.js to find the event handler causing the problem:
Fit.Events.AddHandler(document, "click", function(e)

**Comment by Jemt** [comment]
Fixed - example of Dispose now working properly:
http://fiddle.jshell.net/g5uxrmvt/
