### ISSUE TITLE
Input in DesignMode (CKEditor): Uncaught TypeError: Cannot read property 'setSize' of undefined

### ISSUE THREAD

**Issue by Jemt** [Jemt/Fit.UI#34]
Use https://jsfiddle.net/towy2skm/8/ to reproduce the error.
Simply click the "Create editor" button to trigger the error (check Console in Developer Tools).

![image](https://user-images.githubusercontent.com/1258714/42307393-95774c0a-8032-11e8-82e3-4507712aa841.png)

```
ckeditor.js:332 Uncaught TypeError: Cannot read property 'setSize' of undefined
    at a.CKEDITOR.editor.resize (ckeditor.js:332)
    at updateDesignEditorSize (Fit.UI.js:14525)
    at Fit.Controls.Input.Width (Fit.UI.js:14058)
    at window.createEditor ((index):53)
    at HTMLButtonElement.onclick ((index):78)
```

**Comment by Jemt** [comment]
Also move selected code to the beginning of createEditor() since it results in inconsistent behaviour. The first time the editor is created it works fine even when the element is not rooted due to async. loading of CKEditor.

![image](https://user-images.githubusercontent.com/1258714/43035744-3e014de8-8cf5-11e8-94ab-ecfae058512a.png)

**Comment by FlowIT-JIT** [comment]
This bug went unnoticed for a long time because it only happened when CKEditor resources had already been loaded, meaning the bug would only reveal itself when creating editors dynamically after page load.
