### ISSUE TITLE
DatePicker's calendar widget hidden behind Dialog

### ISSUE THREAD

**Issue by Jemt** [Jemt/Fit.UI#36]
See https://jsfiddle.net/Jemt/1v5fjszn/4/

Notice how the DatePicker's calendar widgets is hidden behind the dialog. We need to raise it's z-index to 1300 like done for ContextMenu (https://github.com/Jemt/Fit.UI/issues/28). The problem with the calendar widget is identical to the one we had for ContextMenu.

![image](https://user-images.githubusercontent.com/1258714/43034871-d9832018-8ce4-11e8-9fe5-fcb260792735.png)

**Comment by FlowIT-JIT** [comment]
Fixed: https://github.com/Jemt/Fit.UI/commit/2804b0867107bea7cce5a97a7e7f53f8ef563f4a
