### ISSUE TITLE
HTML Editor: Does not adopt font size of page

### ISSUE THREAD

**Issue by Jemt** [Jemt/Fit.UI#72]
The HTML editor should adopt the font size from its container. Currently it seems a hardcoded value is used.

![image](https://user-images.githubusercontent.com/1258714/62568149-e5180680-b88c-11e9-9d6b-5c667f9029d4.png)

**Comment by FlowIT-JIT** [comment]
Fixed - editor is no longer encapsulated in an iFrame but uses an editable div instead.
