### ISSUE TITLE
WSTreeView.OnRequest eventArgs.SelectAll always False

### ISSUE THREAD

**Issue by FlowIT-JIT** [Jemt/Fit.UI#90]
Bug found in WSTreeView.OnRequest(function(sender, eventArgs) { ... });

eventArgs.SelectAll is always False, so doing e.g. server side optimization based on this value is no longer possible.

Working example (based on Fit.UI v. 1.0.15):
https://jsfiddle.net/pskftmg8/
Right click _Testers_ and click _Select all_. Notice how eventArgs are written to the browser console where the SelectAll property has the expected boolean value of _true_.

Broken example (based on Fit.UI v. 1.8.15):
https://jsfiddle.net/pskftmg8/1/
(See browser console - notice how SelectAll is always False when data is fetched)

**Comment by FlowIT-JIT** [comment]
We could consider getting rid of the SelectAll property on the event args objekt - perhaps just hardcode it to _false_ to avoid breaking backward compatibility.

Instead we could create a new event that is triggered immediately when the user invokes SelectAll - the existing event, _OnSelectAll_ does not fire until _after_ data has finished loading. So what we need is an event such as _OnSelectingAll_ which fires immediately, and supports suppressing the event by returning _false_ which would also be a useful feature.

The new event can be used by the developer to set a flag that is used in the OnRequest event to do what ever optimization is needed.

Furthermore we would be able to warn - and cancel - Select All for large amounts of data.

In addition we would get rid of internal state that is hard to keep track of within the control (internal WSSelectAll flag).

**Comment by Jemt** [comment]
Fixed existing implementation so that eventArgs.SelectAll works again.
