### ISSUE TITLE
Improve type definitions for TypeScript

### ISSUE THREAD

**Issue by Jemt** [Jemt/Fit.UI#99]
Fit.UI lacks type information for function arguments passed to callbacks (e.g. OnChange, OnBlur, OnOpen, etc.). It also return objects such as { X: number, Y: number } , { Width: number, Height: number }, and { Value: number, Unit: string }.

We need to enrich the type definition file even more which involves improvements to both SimpleDocs and the TypeScript typedef generator.

**Comment by FlowIT-JIT** [comment]
Search for:
_returns="object"_ (functions returning anonymous objecs)
_type="function"_ (functions accepting callback functions which might receive arguments.

**Comment by FlowIT-JIT** [comment]
Basically, search for the following using RegEx:
"(function|array|object)
It will find function argument types, return types, and class members which are to losely typed.

Furthermore, search for the following using RegEx:
///.*null
This will help us identify the possibility of null values which might not have been described as possible argument type value or return value.

**Comment by FlowIT-JIT** [comment]
Also look out for the use of fixed string values, e.g. Fit.Http.Method(..) which only accept values such as "GET", "POST", "DELETE", etc.

**Comment by FlowIT-JIT** [comment]
Fit.UI 2.0 introduces a 100% strongly typed API
